# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publishing

on:
  workflow_dispatch:
    inputs:
      version:
        description: Either a SemVer or patch, minor, major
        required: false
        default: patch

jobs:
  publishu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          # - 12.x
          # - 14.x
          - 16.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      # - run: git config user.email "zeropaper+vf-ci@irata.ch"
      # - run: git config user.name "Valentin Vago as CI"
      # - run: cat package.json
      # - run: npm version ${{ github.event.inputs.version }}
      # - run: cat package.json
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          # skip-commit: 'true'
          git-message: 'chore(release): {version}'
          output-file: 'CHANGELOG.md'
          git-user-name: 'Valentin Vago as CI'
          git-user-email: 'zeropaper+vf-ci@irata.ch'
      # - run: cat package.json
      - run: git status
      # - run: npx vsce verify-pat visual-fiha -p ${{ secrets.VS_MARKETPLACE_TOKEN }}
      - run: npx vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}
      # - run: git add package* CHANGELOG.md
      # - run: git commit -m "chore(release)"
      - run: git push
