# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publishing

on:
  workflow_dispatch:
    inputs:
      version:
        description: Either a SemVer or patch, minor, major
        required: false
        default: patch

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 20.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          git-message: 'chore(release): {version}'
          output-file: 'CHANGELOG.md'
          git-user-name: 'Valentin Vago as CI'
          git-user-email: 'zeropaper+vf-ci@irata.ch'
      
      - run: git status
      
      - name: Publish to VS Marketplace
        run: pnpm exec vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}
      
      - run: git push
