# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Package

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          # - 12.x
          # - 14.x
          - 16.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run package
      # release:
      #   runs-on: ubuntu-latest
      #   needs: package
      #   steps:
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          path: '~/work/visual-fiha/visual-fiha/*.vsix'
          # name: vscode-extension
          # retention-days: 5
